"*.{js,jsx,ts,tsx}":
  - pnpm run lint-js
  - pnpm run format --write

"*.json":
  - pnpm run format --write

"*{css,scss}":
  - pnpm run lint-styles
  - pnpm run format --write

"src/app/styles/_colors.scss":
  - pnpm run utils:sync-colors
  - git add src/shared/styles/colors.ts

"src/shared/assets/icons/!(*.raw).svg":
  - pnpm run svg:optimize -i
