export const EMPLOYEES_KEY = 'EMPLOYEES_KEY';
export const EMPLOYEE_KEY = 'EMPLOYEE_KEY';
export const ADD_EMPLOYEE_KEY = 'ADD_EMPLOYEE_KEY';
export const EDIT_EMPLOYEE_KEY = 'EDIT_EMPLOYEE_KEY';
export const EDIT_EMPLOYEE_STATE_KEY = 'EDIT_EMPLOYEE_STATE_KEY';
export const EDIT_EMPLOYEE_PASSWORD_KEY = 'EDIT_EMPLOYEE_PASSWORD_KEY';
export const DELETE_EMPLOYEE_KEY = 'DELETE_EMPLOYEE_KEY';
