export const neutral0: string;
export const neutral600: string;
export const neutral900: string;
export const primary20: string;
export const primary50: string;
export const primary100: string;
export const primary300: string;
export const primary500: string;
export const primary700: string;
