/** Generated via `utils:sync-colors`. Do not edit manually. */
export const colors = {
    neutral1: 'var(--neutral-1)',
    neutral2: 'var(--neutral-2)',
    neutral3: 'var(--neutral-3)',
    neutral4: 'var(--neutral-4)',
    neutral5: 'var(--neutral-5)',
    neutral6: 'var(--neutral-6)',
    neutral7: 'var(--neutral-7)',
    neutral8: 'var(--neutral-8)',
    neutral9: 'var(--neutral-9)',
    neutral10: 'var(--neutral-10)',
    red: 'var(--red)',
    primary20: 'var(--primary-20)',
    primary50: 'var(--primary-50)',
    primary100: 'var(--primary-100)',
    primary300: 'var(--primary-300)',
    primary500: 'var(--primary-500)',
    primary700: 'var(--primary-700)',
    taptima: 'var(--taptima)',
};
