import type { User } from './model/types/user';
import { RoleTypeEnum } from './model/types/roleTypeEnum';

export const EMPLOYEES_MOCK: User[] = [
    {
        id: 1,
        lastname: 'Петровская',
        firstname: 'Ольга',
        middlename: 'Дмитриевна',
        role: RoleTypeEnum.RoleAdmin,
        email: 'asteward@mail.ru',
        phone: '+7 (903) 880-93-38',
        banned: false,
    },
    {
        id: 2,
        lastname: 'Кулешова',
        firstname: 'Елена',
        middlename: 'Валерьевна',
        role: RoleTypeEnum.RoleSuperAdmin,
        phone: '+7 (903) 679-96-15',
        email: 'astewardwiyruefhwl@mail.ru',
        banned: false,
    },
    {
        id: 3,
        lastname: 'Кулешова',
        firstname: 'Елена',
        middlename: 'Валерьевна',
        role: RoleTypeEnum.RoleSuperAdmin,
        phone: '+7 (903) 679-96-14',
        email: 'khowarduweb@mail.ru',
        banned: false,
    },
    {
        id: 4,
        lastname: 'Петровская',
        firstname: 'Ольга',
        middlename: 'Дмитриевна',
        role: RoleTypeEnum.RoleAdmin,
        phone: '+7 (903) 880-91-85',
        email: 'arussel@mail.ru',
        banned: false,
    },
    {
        id: 5,
        lastname: 'Василенко',
        firstname: 'Кирилл',
        middlename: 'Никитич',
        role: RoleTypeEnum.RoleSuperAdmin,
        phone: '+7 (903) 840-31-53',
        email: 'afisherlala@mail.ru',
        banned: false,
    },
    {
        id: 6,
        lastname: 'Василенко',
        firstname: 'Карл',
        middlename: 'Николаевич',
        role: RoleTypeEnum.RoleSuperAdmin,
        phone: '+7 (903) 880-93-38',
        email: 'prichards@mail.ru',
        banned: true,
    },
    {
        id: 7,
        lastname: 'Вечерняя',
        firstname: 'Зоря',
        middlename: 'Сергеевна',
        role: RoleTypeEnum.RoleAdmin,
        phone: '+7 (903) 880-91-85',
        email: 'cwilliamson@mail.ru',
        banned: true,
    },
];
