import { asset } from 'shared/lib/helpers/asset';
import { API_BASE_URL } from './env';

export const SITE_NAME = '';
export const TITLE = 'Create Next App';
export const DESCRIPTION = 'Generated by create next app';
export const KEYWORDS = '';
export const MAIN_IMAGE = API_BASE_URL + asset('mstile-150x150.png');
export const REGION = 'RU';
export const POSTAL_CODE = '';
export const COUNTRY_NAME = 'RU';
export const LOCALITY = '';
export const ADDRESS = '';
export const LATITUDE = '';
export const LONGITUDE = '';
export const EMAIL = '';
export const PHONE = '';
