export const ADD_EMPLOYEE_KEY = 'ADD_EMPLOYEE_KEY';
export const EDIT_EMPLOYEE_KEY = 'UPDATE_EMPLOYEE_KEY';
export const DELETE_EMPLOYEE_KEY = 'DELETE_EMPLOYEE_KEY';
export const BLOCK_EMPLOYEE_KEY = 'BLOCK_EMPLOYEE_KEY';
export const CHANGE_PASSWORD_KEY = 'CHANGE_PASSWORD_KEY';
